/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ACValidatorLazyImport = createFileRoute('/ACValidator')()
const ACCalculatorLazyImport = createFileRoute('/ACCalculator')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ACValidatorLazyRoute = ACValidatorLazyImport.update({
  path: '/ACValidator',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ACValidator.lazy').then((d) => d.Route))

const ACCalculatorLazyRoute = ACCalculatorLazyImport.update({
  path: '/ACCalculator',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ACCalculator.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ACCalculator': {
      id: '/ACCalculator'
      path: '/ACCalculator'
      fullPath: '/ACCalculator'
      preLoaderRoute: typeof ACCalculatorLazyImport
      parentRoute: typeof rootRoute
    }
    '/ACValidator': {
      id: '/ACValidator'
      path: '/ACValidator'
      fullPath: '/ACValidator'
      preLoaderRoute: typeof ACValidatorLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/ACCalculator': typeof ACCalculatorLazyRoute
  '/ACValidator': typeof ACValidatorLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/ACCalculator': typeof ACCalculatorLazyRoute
  '/ACValidator': typeof ACValidatorLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/ACCalculator': typeof ACCalculatorLazyRoute
  '/ACValidator': typeof ACValidatorLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ACCalculator' | '/ACValidator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ACCalculator' | '/ACValidator'
  id: '__root__' | '/' | '/ACCalculator' | '/ACValidator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ACCalculatorLazyRoute: typeof ACCalculatorLazyRoute
  ACValidatorLazyRoute: typeof ACValidatorLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ACCalculatorLazyRoute: ACCalculatorLazyRoute,
  ACValidatorLazyRoute: ACValidatorLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ACCalculator",
        "/ACValidator"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/ACCalculator": {
      "filePath": "ACCalculator.lazy.tsx"
    },
    "/ACValidator": {
      "filePath": "ACValidator.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
