/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HPCalculatorLazyImport = createFileRoute('/HPCalculator')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HPCalculatorLazyRoute = HPCalculatorLazyImport.update({
  path: '/HPCalculator',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/HPCalculator.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/HPCalculator': {
      id: '/HPCalculator'
      path: '/HPCalculator'
      fullPath: '/HPCalculator'
      preLoaderRoute: typeof HPCalculatorLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/HPCalculator': typeof HPCalculatorLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/HPCalculator': typeof HPCalculatorLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/HPCalculator': typeof HPCalculatorLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/HPCalculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/HPCalculator'
  id: '__root__' | '/' | '/HPCalculator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  HPCalculatorLazyRoute: typeof HPCalculatorLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  HPCalculatorLazyRoute: HPCalculatorLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/HPCalculator"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/HPCalculator": {
      "filePath": "HPCalculator.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
